### ISSUE TITLE
TypeError: 'int' object isn't iterable Micropython 1.19.1

### ISSUE THREAD

**Issue by Ajb2k3** [rsc1975/micropython-sht30#4]
>>> temperature, humidity = sensor.measure()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sht30.py", line 136, in measure
  File "sht30.py", line 100, in send_cmd
TypeError: 'int' object isn't iterable

**Comment by ravenium** [comment]
EDIT: If you're getting this, it means your SHT30 likely isn't connected properly.  Try running this:

from machine import I2C, Pin

i2c = I2C(scl=Pin(5),sda=Pin(4))

i2c.scan()

If you get an empty set [], it means it couldn't find your SHT30.

**Comment by elschopi** [comment]
Grave digger here(seeing how long ago the last comment is)! Just began messing around with those SHT30 sensors, trying to expand my indoor sensor suite. I'm currently running Micropython 1.17 on an ESP32 dev board (the project is a bit older). Currently I'm using a BME280, an DS18B20 and a Pt100 (via ADS1115). I use a SPI TFT Display to visualize data, and send all data to a local influxdb via MQTT and NodeRED.
I've now added the SHT30 sensor on my I2C bus. When I try it out "stand-alone" in it's own little module, it works fine. However when I integrate it into my code, I get the "'int' object isn't iterable" error. 
I can read the sensor once and get data back, but as soon as my loop comes back to it after about 30 secons sleep time, I get that error.
So I'm pretty sure it's connected properly, because in a separate .py it works. 
What could cause that behaviour?
